#!/usr/bin/env bash
# PreToolUse(Bash) hook — evidence is immutable, and the machine files have one writer.
# Denies commands that would delete or rewrite candidate dirs, population.json,
# LEDGER.md, REPORT.md or events.jsonl. Exit 2 blocks the call and shows stderr to
# the agent; the message names the `lab` subcommand it should have used.
set -uo pipefail

LAB_HOOK_INPUT=$(cat 2>/dev/null || echo '{}')
export LAB_HOOK_INPUT

python3 - <<'PY'
import json, os, re, shlex, sys

try:
    data = json.loads(os.environ.get("LAB_HOOK_INPUT", "{}"))
except Exception:
    sys.exit(0)

EVIDENCE = r"(candidates/|events\.jsonl|LEDGER\.md|population\.json|REPORT\.md)"
MACHINE = r"(events\.jsonl|population\.json|FORMAT\.json|fitness\.json|finding\.json|LEDGER\.md)"

# The editing tools reach the same files without a shell: the machine files have one
# writer whichever tool is used, and a worker edits only its own candidate dir.
tool = data.get("tool_name")
if tool in ("Write", "Edit", "MultiEdit", "NotebookEdit"):
    inp = data.get("tool_input") or {}
    fp = str(inp.get("file_path") or inp.get("notebook_path") or "")
    fp = fp.strip()
    if fp:
        # resolve against the tool's cwd, then lexically: candidates/c0004/../c0001/x is
        # c0001's, and ../c0001/x from inside c0004 is too
        fp = os.path.normpath(os.path.join(data.get("cwd") or os.getcwd(), fp))
    if re.search(rf"(?:^|/){MACHINE}$", fp):
        print(f"Blocked: {tool} {fp} — the machine files (population.json, LEDGER.md, "
              "fitness.json, finding.json, events.jsonl, FORMAT.json) have exactly one writer: "
              "`tools/lab`.", file=sys.stderr)
        sys.exit(2)
    if os.environ.get("LAB_ROLE") == "worker" and fp:
        own_dir = os.path.normpath(os.environ.get("LAB_CANDIDATE_DIR", "") or "")
        own = os.path.basename(own_dir)
        m = re.search(r"/candidates/(c\d{4})(?:/|$)", fp)
        inside_own = own_dir and (fp == own_dir or fp.startswith(own_dir + os.sep))
        if m and own and not inside_own:
            print(f"Blocked: {tool} {fp} — that writes into another candidate's dir. A worker "
                  f"writes only inside its own ({own}).", file=sys.stderr)
            sys.exit(2)
    sys.exit(0)
if tool != "Bash":
    sys.exit(0)
cmd = (data.get("tool_input") or {}).get("command", "")
if not cmd:
    sys.exit(0)

START = r"(?:^|[;&|]\s*|\$\(\s*)"
NOSEP = r"[^;&|]*"

RULES = [
    (rf"{START}(?:sudo\s+)?(?:rm|rmdir|shred|unlink|trash)\b{NOSEP}{EVIDENCE}",
     "that deletes evidence. Candidate dirs, LEDGER rows, REPORT.md and events.jsonl are "
     "append-only history — a failed, killed or invalid candidate is data. If a candidate "
     "is misleading, say so in the next candidate's summary.md and in the report instead."),
    (rf"{START}(?:sudo\s+)?mv\b{NOSEP}{EVIDENCE}",
     "that moves evidence out from under its recorded path. Paths in LEDGER.md, "
     "population.json, config.json and the event feed must keep resolving."),
    (rf"{START}(?:sudo\s+)?git\s+(?:rm|clean|checkout\s+--|restore)\b{NOSEP}{EVIDENCE}",
     "that removes or reverts committed evidence."),
    (rf">{NOSEP}?\s*\.?/?{MACHINE}",
     "that writes the machine files directly. population.json, LEDGER.md, fitness.json and "
     "events.jsonl have exactly one writer: `tools/lab` (`lab run`, `lab eval`, `lab log`); "
     "FORMAT.json is generated by `lab format sync`."),
    (rf"{START}(?:tee|truncate|dd)\b{NOSEP}{MACHINE}",
     "that rewrites a machine file. Use `tools/lab log` / `tools/lab format sync`; the "
     "loop's own files are written by `lab run`."),
    (rf"{START}(?:sudo\s+)?(?:cp|install|mv|ln|rsync|touch)\b{NOSEP}{MACHINE}",
     "that creates or replaces a machine file by copying. population.json, LEDGER.md, "
     "fitness.json, finding.json, events.jsonl and FORMAT.json are written only by "
     "`tools/lab`; a finding.json a worker writes is quarantined at settlement, not adopted."),
    (rf"{START}(?:sudo\s+)?(?:sed|perl)\b{NOSEP}-[a-zA-Z]*i{NOSEP}{MACHINE}",
     "that edits a machine file in place. Events and ledger rows are never edited (append "
     "a correcting `lab log note` instead); fitness.json and finding.json are written only "
     "by `lab`."),
    (rf"curl{NOSEP}\|\s*(?:ba|z|)sh",
     "that pipes a download straight into a shell."),
]

# A worker session (LAB_ROLE=worker, launched by `lab run`) may touch only its own
# candidate dir and must never look for the hidden labels. The job card says so; this
# makes the attempt visible and blocked at the tool boundary as well.
if os.environ.get("LAB_ROLE") == "worker":
    inp = data.get("tool_input") or {}
    # A deliberately shallow guard, not a Bash parser. Skip conventional heredoc
    # bodies (including <<- and multiple documents), but inspect their headers and
    # commands after their delimiters. CLI controls and owned-process containment
    # enforce lifetime even for shell syntax this heuristic does not recognize.
    detached = inp.get("run_in_background")
    heredocs = []
    for line in cmd.splitlines():
        if heredocs:
            delimiter, strip_tabs = heredocs[0]
            if (line.lstrip("\t") if strip_tabs else line) == delimiter:
                heredocs.pop(0)
            continue
        lexer = shlex.shlex(line, posix=False, punctuation_chars=";&|<>")
        lexer.whitespace_split = True
        try:
            tokens = list(lexer)
        except ValueError:
            # Do not interpret the remaining quoted body as shell commands. Only
            # this heuristic fails open; explicit background and RULES still apply.
            detached = inp.get("run_in_background")
            break
        for i, token in enumerate(tokens):
            if token == "<<" and i + 1 < len(tokens):
                word = tokens[i + 1]
                strip_tabs = word.startswith("-")
                word = word[1:] if strip_tabs else word
                if re.fullmatch(r"(?:[\w]+|'[\w]+'|\"[\w]+\")", word):
                    heredocs.append((word.strip("'\""), strip_tabs))
            if token in ("&", "&;"):
                detached = True
            # Executables only at simple command positions, never prose arguments.
            if i == 0 or tokens[i - 1] in (";", "&&", "||", "|", "&"):
                executable = os.path.basename(token.strip("'\""))
                if executable in ("nohup", "setsid", "disown"):
                    detached = True
                if executable == "lab" and tokens[i + 1:i + 3] in (["watch", "start"], ["watch", "_run"]):
                    detached = True
    if detached:
        print("Blocked: workers must run synchronously in the foreground with a bounded "
              "Bash timeout. No background tasks or nested watchers; wait for exit, "
              "check predictions, and write summary.md before ending the session.", file=sys.stderr)
        sys.exit(2)
    RULES.append((r"LAB_PRIVATE|labels\.json|/labels(?:/|\b)",
                  "a worker never reads labels. Fitness comes from `lab eval`, which is the "
                  "only reader of the search and final splits."))
    own = os.environ.get("LAB_CANDIDATE_DIR", "")
    if own and re.search(r"candidates/c\d{4}", cmd):
        for m in re.finditer(r"candidates/(c\d{4})", cmd):
            if m.group(1) not in os.path.basename(own) and re.search(
                    rf"(?:>|>>|tee|cp|mv|rm|sed\s+-i|touch|mkdir)[^;&|]*candidates/{m.group(1)}", cmd):
                print(f"Blocked: `{cmd}` — that writes into another candidate's dir. A worker "
                      f"writes only inside {own}.", file=sys.stderr)
                sys.exit(2)

for pattern, why in RULES:
    if re.search(pattern, cmd):
        print(f"Blocked: `{cmd}` — {why}", file=sys.stderr)
        sys.exit(2)
sys.exit(0)
PY
