#!/usr/bin/env bash
# PreToolUse(Bash) hook — evidence is immutable, and the machine files have one writer.
# Denies commands that would delete or rewrite candidate dirs, population.json,
# LEDGER.md, REPORT.md or events.jsonl. Exit 2 blocks the call and shows stderr to
# the agent; the message names the `lab` subcommand it should have used.
set -uo pipefail

LAB_HOOK_INPUT=$(cat 2>/dev/null || echo '{}')
export LAB_HOOK_INPUT

python3 - <<'PY'
import json, os, re, sys

try:
    data = json.loads(os.environ.get("LAB_HOOK_INPUT", "{}"))
except Exception:
    sys.exit(0)

if data.get("tool_name") != "Bash":
    sys.exit(0)
cmd = (data.get("tool_input") or {}).get("command", "")
if not cmd:
    sys.exit(0)

EVIDENCE = r"(candidates/|events\.jsonl|LEDGER\.md|population\.json|REPORT\.md)"
MACHINE = r"(events\.jsonl|population\.json|FORMAT\.json|fitness\.json|LEDGER\.md)"
START = r"(?:^|[;&|]\s*|\$\(\s*)"
NOSEP = r"[^;&|]*"

RULES = [
    (rf"{START}(?:sudo\s+)?(?:rm|rmdir|shred|unlink|trash)\b{NOSEP}{EVIDENCE}",
     "that deletes evidence. Candidate dirs, LEDGER rows, REPORT.md and events.jsonl are "
     "append-only history — a failed, killed or invalid candidate is data. If a candidate "
     "is misleading, say so in the next candidate's summary.md and in the report instead."),
    (rf"{START}(?:sudo\s+)?mv\b{NOSEP}{EVIDENCE}",
     "that moves evidence out from under its recorded path. Paths in LEDGER.md, "
     "population.json, config.json and the event feed must keep resolving."),
    (rf"{START}(?:sudo\s+)?git\s+(?:rm|clean|checkout\s+--|restore)\b{NOSEP}{EVIDENCE}",
     "that removes or reverts committed evidence."),
    (rf">{NOSEP}?\s*\.?/?{MACHINE}",
     "that writes the machine files directly. population.json, LEDGER.md, fitness.json and "
     "events.jsonl have exactly one writer: `tools/lab` (`lab run`, `lab eval`, `lab log`); "
     "FORMAT.json is generated by `lab format sync`."),
    (rf"{START}(?:tee|truncate|dd)\b{NOSEP}{MACHINE}",
     "that rewrites a machine file. Use `tools/lab log` / `tools/lab format sync`; the "
     "loop's own files are written by `lab run`."),
    (rf"{START}sed\b{NOSEP}-i{NOSEP}(events\.jsonl|population\.json|LEDGER\.md)",
     "that edits history in place. Events and ledger rows are never edited; append a "
     "correcting `lab log note` instead."),
    (rf"curl{NOSEP}\|\s*(?:ba|z|)sh",
     "that pipes a download straight into a shell."),
]

# A worker session (LAB_ROLE=worker, launched by `lab run`) may touch only its own
# candidate dir and must never look for the hidden labels. The job card says so; this
# makes the attempt visible and blocked at the tool boundary as well.
if os.environ.get("LAB_ROLE") == "worker":
    RULES.append((r"LAB_PRIVATE|labels\.json|/labels(?:/|\b)",
                  "a worker never reads labels. Fitness comes from `lab eval`, which is the "
                  "only reader of the search and final splits."))
    own = os.environ.get("LAB_CANDIDATE_DIR", "")
    if own and re.search(r"candidates/c\d{4}", cmd):
        for m in re.finditer(r"candidates/(c\d{4})", cmd):
            if m.group(1) not in os.path.basename(own) and re.search(
                    rf"(?:>|>>|tee|cp|mv|rm|sed\s+-i|touch|mkdir)[^;&|]*candidates/{m.group(1)}", cmd):
                print(f"Blocked: `{cmd}` — that writes into another candidate's dir. A worker "
                      f"writes only inside {own}.", file=sys.stderr)
                sys.exit(2)

for pattern, why in RULES:
    if re.search(pattern, cmd):
        print(f"Blocked: `{cmd}` — {why}", file=sys.stderr)
        sys.exit(2)
sys.exit(0)
PY
